"""Canonical safe-offline stage registry for workspace analysis."""

from finsec.workspace_analysis.domain import WorkspaceAnalysisStage

WORKSPACE_ANALYSIS_STAGES: tuple[WorkspaceAnalysisStage, ...] = (
    WorkspaceAnalysisStage(
        stage_id="workspace_validation",
        display_name="Workspace validation",
        conceptual_stages=["workspace validation"],
        required=True,
        inputs=["target.yaml"],
        outputs=[],
        service_name="WorkspacePaths/TargetDocument validation",
        freshness_condition="Always validate the selected workspace and target document.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="configuration_scope",
        display_name="Configuration and scope loading",
        conceptual_stages=["configuration and scope loading"],
        required=True,
        prerequisites=["workspace_validation"],
        inputs=["target.yaml", "scope/program.md", "scope/scope.md", "scope/restrictions.md"],
        outputs=[],
        service_name="TargetDocument and scope policy",
        freshness_condition="Always load current configuration; this stage is read-only.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="capture_observation_validation",
        display_name="Capture and observation validation",
        conceptual_stages=["capture validation", "observation validation"],
        required=True,
        prerequisites=["workspace_validation", "configuration_scope"],
        inputs=["captures/captures.yaml", "observations/normalized/observations.yaml"],
        outputs=[],
        service_name="CaptureStore and ObservationStore validation",
        freshness_condition="Always validate current factual inputs; ingestion is never run.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="classification_inventory",
        display_name="Classification and endpoint inventory",
        conceptual_stages=[
            "classification",
            "endpoint/resource inventory",
            "capture analysis refresh",
        ],
        required=True,
        prerequisites=["capture_observation_validation"],
        inputs=["target.yaml", "observations/normalized/observations.yaml"],
        outputs=[
            "api/endpoints.yaml",
            "captures/captures.yaml",
            "model/controlled-ownership.yaml",
        ],
        service_name="finsec.normalization.inventory.build_inventory",
        freshness_condition=(
            "Use canonical inventory provenance; rebuild when missing or stale, and always on "
            "force."
        ),
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="actor_authentication_analysis",
        display_name="Actor and authentication analysis",
        conceptual_stages=["actor analysis", "authentication analysis"],
        required=False,
        prerequisites=["configuration_scope", "capture_observation_validation"],
        inputs=["target.yaml", "model/actors.yaml", "captures/captures.yaml"],
        outputs=[],
        service_name="canonical readiness actor resolver",
        freshness_condition="Always resolve current secret-free actor readiness; read-only.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="ownership_baseline_analysis",
        display_name="Ownership baseline analysis",
        conceptual_stages=["ownership baseline analysis"],
        required=False,
        prerequisites=["classification_inventory"],
        inputs=["model/controlled-ownership.yaml", "api/endpoints.yaml"],
        outputs=[],
        service_name="ControlledOwnershipStore validation",
        freshness_condition="Rebuilt by inventory and then validated independently.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="actor_resource_modeling",
        display_name="Actor and resource modeling",
        conceptual_stages=["resource modeling", "authorization views", "legacy workflow maps"],
        required=True,
        prerequisites=["classification_inventory"],
        inputs=["target.yaml", "observations/normalized/observations.yaml", "api/endpoints.yaml"],
        outputs=[
            "model/actors.yaml",
            "model/resources.yaml",
            "model/architecture.md",
            "model/authorization.md",
            "model/workflows.md",
            "model/state-machines.md",
        ],
        service_name="finsec.modeling.generator.generate_model",
        freshness_condition=(
            "Use canonical model provenance; rebuild when missing or stale, and always on force."
        ),
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="security_invariant_generation",
        display_name="Security invariant generation",
        conceptual_stages=["invariant generation"],
        required=False,
        prerequisites=["actor_resource_modeling"],
        inputs=["api/endpoints.yaml", "model/resources.yaml"],
        outputs=["model/invariants.yaml"],
        service_name="finsec.modeling.invariants.generate_invariants",
        freshness_condition=(
            "Use canonical invariant provenance; rebuild when missing or stale, and always on "
            "force."
        ),
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="security_hypothesis_generation",
        display_name="Security hypothesis generation",
        conceptual_stages=[
            "security hypothesis generation",
            "domain-intent validation",
            "unified readiness evaluation",
            "semantic deduplication",
            "campaign construction",
            "suppression decisions",
            "research-task calibration",
        ],
        required=False,
        prerequisites=["security_invariant_generation"],
        inputs=[
            "target.yaml",
            "observations/normalized/observations.yaml",
            "api/endpoints.yaml",
            "model/resources.yaml",
            "model/invariants.yaml",
        ],
        outputs=["hypotheses/backlog.yaml"],
        service_name="finsec.hypotheses.generator.generate_hypotheses",
        freshness_condition=(
            "Use canonical hypothesis provenance; rebuild when missing or stale, and always on "
            "force."
        ),
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="behavior_workflow_analysis",
        display_name="Behavior, workflow, and business-logic analysis",
        conceptual_stages=[
            "behavior extraction",
            "workflow reconstruction",
            "workflow family construction",
            "business invariant generation",
            "business-logic hypothesis generation",
            "precision clustering",
            "cross-generator clustering",
        ],
        required=False,
        prerequisites=["actor_resource_modeling"],
        inputs=[
            "target.yaml",
            "observations/normalized/observations.yaml",
            "api/endpoints.yaml",
            "model/resources.yaml",
            "hypotheses/backlog.yaml",
        ],
        outputs=[
            "behavior/actions.yaml",
            "behavior/resource-instances.yaml",
            "behavior/workflow-instances.yaml",
            "behavior/workflow-families.yaml",
            "behavior/states.yaml",
            "behavior/transitions.yaml",
            "behavior/propagation-links.yaml",
            "behavior/graphs/",
            "model/business-invariants.yaml",
            "hypotheses/business-logic.yaml",
            "hypotheses/backlog.yaml",
        ],
        service_name="finsec.behavior.analysis.analyze_business_logic",
        freshness_condition=(
            "No complete behavior provenance exists; safely rerun this deterministic offline stage "
            "in default and force modes."
        ),
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="domain_intent_readiness_validation",
        display_name="Unified intent and readiness validation",
        conceptual_stages=["domain-intent validation", "unified readiness evaluation"],
        required=False,
        prerequisites=["behavior_workflow_analysis"],
        inputs=["hypotheses/backlog.yaml"],
        outputs=[],
        service_name="HypothesisStore shared semantic/readiness contracts",
        freshness_condition="Always validate persisted shared contracts; read-only.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="clustering_deduplication_campaigns",
        display_name="Clustering, deduplication, and campaigns",
        conceptual_stages=[
            "cross-generator clustering",
            "semantic deduplication",
            "campaign construction",
        ],
        required=False,
        prerequisites=["domain_intent_readiness_validation"],
        inputs=["hypotheses/backlog.yaml", "hypotheses/business-logic.yaml"],
        outputs=[],
        service_name="HypothesisStore campaign and presentation contracts",
        freshness_condition="Always validate persisted grouping decisions; read-only.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="suppression_research_calibration",
        display_name="Suppression and research-task calibration",
        conceptual_stages=["suppression decisions", "research-task calibration"],
        required=False,
        prerequisites=["clustering_deduplication_campaigns"],
        inputs=["api/endpoints.yaml", "hypotheses/backlog.yaml"],
        outputs=[],
        service_name="presentation visibility and hypothesis population",
        freshness_condition="Always summarize current deterministic decisions; read-only.",
        failure_allows_continue=True,
    ),
    WorkspaceAnalysisStage(
        stage_id="final_workspace_status",
        display_name="Final workspace status aggregation",
        conceptual_stages=["final workspace status aggregation"],
        required=True,
        prerequisites=["workspace_validation"],
        inputs=["all current workspace artifacts"],
        outputs=[],
        service_name="finsec.readiness.resolver.resolve_workspace_readiness",
        freshness_condition="Always compute current canonical readiness; read-only.",
        failure_allows_continue=True,
    ),
)

STAGE_BY_ID = {stage.stage_id: stage for stage in WORKSPACE_ANALYSIS_STAGES}
